#!/usr/bin/env ruby

require 'mkalias'

VALID_OPTIONS = ['new', 'list']

def usage
  puts "Usage: mkalias [option]"
  puts "option: new \t -> mkalias new [alias] [command]"
  puts "option: list \t -> mkalias list"
  abort
end

def new_alias
  if ARGV.count < 3
    usage
  end

  alias_name = ARGV[1]
  command = ARGV[2]
  Mkalias.new_alias(alias_name, command)
end

def list_alias
  alias_names = Mkalias.list_alias

  puts "Registered Alias:"
  alias_names.each do |alias_name|
    puts " - #{alias_name}"
  end
end

def main
  if ARGV.count == 0 || !VALID_OPTIONS.include?(ARGV[0])
    usage
  end

  option = ARGV[0]

  if option == 'new'
    new_alias
  elsif option == 'list'
    list_alias
  end
end


if caller.length == 0
  main
end
